### ISSUE TITLE
Can't edit/update an existing school's EZ Proxy URL

### ISSUE THREAD

**Issue by briandk** [tom5760/chrome-ezproxy#3]
## Overview

I get an error when I try to update the ez proxy URL for Michigan State University. The proper URL (as far as I can tell) for Michigan State should be:

```
http://ezproxy.msu.edu/login?url=$@
```

But right now it's set to `http://web.lexisnexis.com.proxy1.cl.msu.edu/url=$@`
## Expected Behavior

I should be able to edit the proxy by typing in the name of the university and the updated URL to which it should redirect.

![napkin 2 10-04-15 8 47 47 am](https://cloud.githubusercontent.com/assets/330036/10267901/96334ff8-6a74-11e5-9cf8-31ccb087c81a.png)
## Actual Behavior

When I submit this (School Name: Michigan State University; EZProxy URL: http://ezproxy.msu.edu/login?url=$@)

![napkin 2 10-04-15 8 49 21 am](https://cloud.githubusercontent.com/assets/330036/10267905/cdd81dc6-6a74-11e5-871c-206987d8bf4d.png)

I get this error:

> A proxy with that name already exists in the database, please try again.
## Why this is a problem

The Michigan State University proxy URL is hard-coded to Lexis Nexis; it fails on any other electronic resource site:

```
http://web.lexisnexis.com.proxy1.cl.msu.edu/url=$@
```
## What I've currently done as a workaround

I've specified the URL manually in my EZ Proxy options:

```
http://ezproxy.msu.edu/login?url=$@
```

**Comment by tom5760** [comment]
Hey, thanks for the report!  I've been meaning to make this and other improvements, but haven't found the time yet.  I'll try to work on this in the next few days.  What people have done in the past is just submit a new URL with a name like "Michigan State University (Updated)", and then I go in and update it.  For now, I just updated the URL to what you specified.
