### ISSUE TITLE
Add option for users to select multiple schools?

### ISSUE THREAD

**Issue by zkamvar** [tom5760/chrome-ezproxy#4]
Hello,

As I'm currently transitioning between two institutions, I'm allowed to keep my old institution email for a year, meaning that I have access to articles my current institution doesn't and vice-versa.

This is not an uncommon situation for many people and a cool feature to have would be the option to toggle the ability to select from a custom list of institutions. 

Thank you for this extension, by the way. It's helped me immensely when I was writing my dissertation while hiding from my advisor 😆 .

**Comment by tom5760** [comment]
Hey, thanks for the report!  I've not had much time lately to work on this extension unfortunately.  I'll definitely keep a note of this though, hopefully I can come back to this in a few weeks to add this feature.

**Comment by vancleve** [comment]
Would love this addition as well!

**Comment by tom5760** [comment]
Better late than never?  I've just updated a release to the Chrome Web Store (version 17) with support for this.  Let me know if you have any comments.
