### ISSUE TITLE
Harvard proxy redirecting to menu rather than website

### ISSUE THREAD

**Issue by kescobo** [tom5760/chrome-ezproxy#5]
Recently, using the chrome extension with the Harvard proxy redirects to http://ezp-prod1.hul.harvard.edu/menu rather than to the correct url. 

Manually entering the proxy (eg http://ezp-prod1.hul.harvard.edu/login?url=http://www.chronicle.com/article/What-s-New-in-Freshman/240864) still works as expected. 

I'm not sure exactly how long this has been happening, but it worked fine ~ 1 month ago, and has been doing this for at least a week. 

Chrome: Version 60.0.3112.90 (Official Build) (64-bit)
MacOS: v10.12.5
EZProxy: v14

**Comment by tommygober** [comment]
This is happening at University of Texas Rio Grande Valley as well.

I'm suspecting Chrome does not include the http:// or https:// in the url reported back to the Tab object. I'm wondering if the background.js will need to include something to pull the target url's "scheme" to include in the request sent on to EZProxy.

That, or perhaps OCLC updated EZProxy to require a certain "HTTP_REFERER" field

**Comment by tom5760** [comment]
Yeah, something must have changed in Chrome recently.  I'm investigating tonight.

**Comment by tom5760** [comment]
As a workaround, it appears that right-clicking on links and selecting "Open Link with EZProxy" still works.

**Comment by SimpleConjugate** [comment]
The same is occurring for Louisiana Tech University. Instead of selecting by university, choose custom URL and keep the default.

**Comment by tom5760** [comment]
Ok, this turned out to be a easy fix.  Apparently, the "tabs" permission is now required to get the URL of the current tab when you click the extension button.  I've just deployed a new version to the store (version 15), which should be available soon.

**Comment by kescobo** [comment]
Excellent, thanks a bunch!

**Comment by tom5760** [comment]
Quick follow-up.  I've put out a new version that replaces the "tabs" permission with the ["activeTab" permission](https://developer.chrome.com/extensions/activeTab).  This gets rid of the scary warning saying that the extension has access to your browsing history.  I wish I found this earlier...

**Comment by kescobo** [comment]
@tom5760 That's sensible, but you can have my browsing history, I don't care :-P

**Comment by tom5760** [comment]
Unfortunately, a few other people seem to care. 😿 

![uninstall](https://user-images.githubusercontent.com/62623/29178057-700da68e-7dbe-11e7-819c-78044af093cd.png)

**Comment by kescobo** [comment]
😬
