### ISSUE TITLE
Allow binding to reload

### ISSUE THREAD

**Issue by swflint** [tom5760/chrome-ezproxy#8]
Would it be possible to provide a way to bind a key to whatever function reloads the page through the proxy?  For instance, I'd like to be able to use Alt+F5 to reload through the proxy.

**Comment by swflint** [comment]
That'll be awesome.  Hopefully  it gets pushed to the firefox version as well.

**Comment by swflint** [comment]
Helpfully, if you leave `manifest_version` as 2, you should be able to just use `_execute_browser_action`, so it's *just* a modification to the manifest, and nothing else.

**Comment by tom5760** [comment]
> Helpfully, if you leave manifest_version as 2

Yeah... I'm gonna have to update this sooner or later.  We'll see...

**Comment by tom5760** [comment]
I've just submitted v22 to both Chrome and Firefox's extension sites.  It's now manifest v3, and I added the keyboard shortcut.  No idea how long it'll take to publish in the Chrome Web Store, I'll note here once I see it up.

**Comment by swflint** [comment]
Works great on Firefox, thanks!
